//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_market
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_item
    {
        public int cartItemID { get; set; }
        public int cartID { get; set; }
        public int productID { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public short inCart { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
