//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_item
    {
        public long cartItemID { get; set; }
        public long cartID { get; set; }
        public long productID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<short> inCart { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
