//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public long cartID { get; set; }
        public long userID { get; set; }
        public string sessionID { get; set; }
    
        public virtual user user { get; set; }
    }
}
