//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long productID { get; set; }
        public long vendorID { get; set; }
        public long categoryID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<short> availableQTY { get; set; }
        public Nullable<short> CanBeBought { get; set; }
        public string productInfo { get; set; }
        public string sourceOfImage { get; set; }
    
        public virtual vendor vendor { get; set; }
        public virtual product_category product_category { get; set; }
    }
}
