//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_market
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactionID { get; set; }
        public int userID { get; set; }
        public int orderID { get; set; }
        public int status { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public string paymentGatewayID { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
