//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public long vendorID { get; set; }
        public long userID { get; set; }
        public string locationOfStore { get; set; }
        public string info { get; set; }
    
        public virtual user user { get; set; }
    }
}
